(define-module (config home services niri core)
  #:use-module (guix gexp)
  #:use-module (gnu packages base)
  #:export (core-config-patch))

(define (core-config-patch)
  #~(let ((sed-bin (string-append #$sed "/bin/sed")))
      (let ((files (find-files #$output "[.](qml|js|json|kdl|sh|fish|py)$")))
        (for-each make-file-writable files)
        (for-each (lambda (f)
                    (invoke sed-bin "-i" "s|/usr/bin/jq|jq|g" f)
                    (invoke sed-bin "-i" "s|/usr/bin/||g" f)
                    (invoke sed-bin "-i" "s|Process.exec|Quickshell.execDetached|g" f)
                    (unless (or (string-suffix? "Config.qml" f) (string-suffix? ".py" f))
                       (invoke sed-bin "-i" "s|kitty|foot|g" f)
                       (invoke sed-bin "-i" "s|ghostty|foot|g" f))
                    (invoke sed-bin "-i" "s|^#!env |#!/usr/bin/env |g" f)
                    (invoke sed-bin "-i" "s|#!/usr/bin/fish|#!/usr/bin/env fish|g" f)
                    (invoke sed-bin "-i" "s|#!/bin/bash|#!/usr/bin/env bash|g" f))
                  files))))
