(define-module (config home services niri theme)
  #:use-module (guix gexp)
  #:use-module (gnu packages base)
  #:export (theme-config-patch))

(define (theme-config-patch)
  #~(let ((sed-bin (string-append #$sed "/bin/sed"))) 
      (let ((f (string-append #$output "/modules/common/Config.qml"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "s|\"ghostty\"|\"foot\"|g" f)
            (invoke sed-bin "-i" "s|\"kitty\"|\"foot\"|g" f)
            (invoke sed-bin "-i" "s|: \"kitty |: \"foot |g" f)
            (invoke sed-bin "-i" "s|: \"ghostty |: \"foot |g" f)))
      (let ((f (string-append #$output "/services/ThemeService.qml"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "s|Quickshell.execDetached.Directories.wallpaperSwitchScriptPath, .--noswitch..|Quickshell.execDetached([Directories.wallpaperSwitchScriptPath, \"--noswitch\", \"--mode\", (Config.options?.appearance?.customTheme?.darkmode ?? true) ? \"dark\" : \"light\"])|g" f)))
      (let ((f (string-append #$output "/scripts/colors/applycolor.sh"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "s|cp .SCRIPT_DIR/terminal/sequences.txt.|install -m 644 \"$SCRIPT_DIR/terminal/sequences.txt\"|g" f)))
      (let ((f (string-append #$output "/scripts/colors/apply-gtk-theme.sh"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "s|GTK4_CSS=.HOME/.config/gtk-4.0/gtk.css.|GTK4_CSS=\"/home/mou/.cache/matugen/gtk4_extra.css\"|g" f)
            (invoke sed-bin "-i" "s|GTK3_CSS=.HOME/.config/gtk-3.0/gtk.css.|GTK3_CSS=\"/home/mou/.cache/matugen/gtk3_extra.css\"|g" f)))
      (let ((f (string-append #$output "/scripts/colors/switchwall.sh"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "s|cat . .RESTORE_SCRIPT.tmp.|mkdir -p \"$(dirname \"$RESTORE_SCRIPT\")\"; cat > \"$RESTORE_SCRIPT.tmp\"|g" f)))
      (let ((f (string-append #$output "/scripts/colors/generate_terminal_configs.py"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "s|f..home./.config/foot/current-theme.conf.|os.path.expanduser(\"~/.cache/matugen/foot.ini\")|g" f)
            (invoke sed-bin "-i" "s|f..home./.config/foot/colors.ini.|os.path.expanduser(\"~/.cache/matugen/foot.ini\")|g" f)
            (invoke sed-bin "-i" "s|if ensure_line_in_file.|if False and ensure_line_in_file(|g" f)))
      ;; Fix shebang in generate_colors_material.py to work on Guix (no /bin/sh)
      (let ((f (string-append #$output "/scripts/colors/generate_colors_material.py"))) 
         (when (file-exists? f) 
            (invoke sed-bin "-i" "1s|.*|#!/usr/bin/env python3|" f)))))
